//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Registration
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Username is required")]
        [Display(Name ="UserName")]
        public string Username { get; set; }
        [Required(ErrorMessage = "Password is required")]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [Required(ErrorMessage = "This is required")]
        [Display(Name = "Confirm Passowrd")]
        [DataType(DataType.Password)]
        public string ConfirmPassword { get; set; }
    }
}
