//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Productslist
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Name is required")]
        [Display(Name ="Product Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Price is required")]
        [Display(Name = "Price")]
        public decimal Price { get; set; }
        [Required(ErrorMessage = "Quantity is required")]
        [Display(Name = "Quantity")]
        public int Quantity { get; set; }
        [Required(ErrorMessage = "Image is required")]
        [Display(Name = "Image")]
        public string ImagePath { get; set; }
        [Required(ErrorMessage = "Detail is required")]
        [Display(Name = "Detail")]
        public string ShortDescription { get; set; }
        [Required(ErrorMessage = "product detail is required")]
        [Display(Name = "Product Details")]
        public string Detaildescription { get; set; }
        [Required(ErrorMessage = "Category is required")]
        [Display(Name = "Category")]
        public int Category { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        public virtual Category Category1 { get; set; }
    }
}
