//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControlFinalAssignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Registration
    {
        [Required(ErrorMessage = "Id is required")]
        [Display(Name = "Id:")]
        public int id { get; set; }
        [Required(ErrorMessage = "UserName is required")]
        [Display(Name = "UserName:")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Password is required")]
        [DataType(DataType.Password)]
        [MaxLength(15)]
        [Display(Name = "Password:")]
        public string Password { get; set; }
        [Required(ErrorMessage = "ConfirmPassword")]
        [Display(Name = "ConfirmPassword:")]
        [System.ComponentModel.DataAnnotations.Compare("Password", ErrorMessage = "Password Not Matched")]
        public string ConfirmPassword { get; set; }
    }
}
