//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControlFinalAssignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    public partial class userregistration
    {
        [Required(ErrorMessage = "Id is required")]
        [Display(Name = "Id:")]
        public int id { get; set; }
        [Required(ErrorMessage = "Name is required")]
        [Display(Name = "Name:")]
        [StringLength(50, MinimumLength = 3)]
        public string Name { get; set; }
        [Required(ErrorMessage = "Email ID is Required")]
        [DataType(DataType.EmailAddress)]
        [MaxLength(50)]
        [RegularExpression(@"[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}", ErrorMessage = "Incorrect Email Format")]
        [Display(Name = "EmailId:")]
        public string Emailid { get; set; }
        [Required(ErrorMessage = "Designation is required")]
        [Display(Name = "Designation:")]
        public string Designation { get; set; }
        [Required(ErrorMessage = "Address is required")]
        [Display(Name = "Address:")]
        public string Address { get; set; }
        [Display(Name="Age:")]
        [Required(ErrorMessage = "Age is Required")]
        [CustomValidations.CustomAttribute.MinAge(18)]
        public int Age { get; set; }
        [DataType(DataType.PhoneNumber)]
        //[Required(ErrorMessage = "Not a valid Phone number")]
       // [Display(Name = "Phone:")]
        public int Phone { get; set; }
    }
}
